### ISSUE TITLE
Comments on initial zap contract

### ISSUE THREAD

**Issue by larrythecucumber321** [pickle-finance/utility-contracts#1]
Great work on this @UrAvgDeveloper! I think this will totally do what we need it to. Just some comments below to consider:

1. https://github.com/pickle-finance/utility-contracts/blob/345c2a61e5499c6382895d31acdc4fea1a5f64b1/contracts/Pickle_UniV2_ZapIn_V1.sol#L96

I would accept an array of `_swapTargets` in the constructor as there are usually multiple relevant DEXes on a sidechain

2. https://github.com/pickle-finance/utility-contracts/blob/345c2a61e5499c6382895d31acdc4fea1a5f64b1/contracts/Pickle_UniV2_ZapIn_V1.sol#L276

I think it might be a good idea to sanitize inputs here. If the user's deposited ETH amount exceeds `_amount`, then they may have some ETH locked up (and so a refund should be issued). Conversely, the call will fail if `_amount` exceeds, the `msg.value`, and so perhaps `_amount` should be adjusted downwards in such cases.

Also, `WETH` beig a possible `_swapTarget` is a little confusing, as `_swapTarget` is generally reserved for the AMM contract, but I understand you're combining the functionality of 2 different Zapper contracts (first being the user-facing zap, and second being the Uniswap add/swap), so this may be unavoidable.

3. https://github.com/pickle-finance/utility-contracts/blob/345c2a61e5499c6382895d31acdc4fea1a5f64b1/contracts/Pickle_UniV2_ZapIn_V1.sol#L125

Declaration of `_uniswapRouter` appears redundant, given that `_swapTarget` provides identifcal data scenarios not involving ETH. You could get low-level and `abi.decode` the `swapData` to check whether the first `path` address is `WETH` (and initialize WETH address within the constructor based on the first approved target for example). But ultimately, I don't know if this is worth the trouble, but just wanted to hear your thoughts 🙂

**Comment by UrAvgDeveloper** [comment]
Responses:
1. Agreed, will add this. Although we also have another function to add swapTargets later if needed.
2. The check for _amount == msg.value makes a lot of sense. I will add that. Yes regarding WETH as target saves a lot of gas and simplifies things when it comes to zaps including `Native currency` -> 'Native currency pools'.
3. So there are two swaps that happen in the whole flow: First, `From token -> intermediate token` where intermediate token is one of pool token0/token1. This involves the use of swapTarget and swapData where you can use any DEX to do this. The second is converting 1 of the pool tokens (the intermediate token) to the other pool token (50-50 ratio) which leverages the pool's liquidity itself to do the necessary swap. Here is where the uniswapRouter is used and is different from swapTarget/Data. For the second swap I wanted to make the uniswapRouter part of zap so that it is generic enough to support any protocol.

**Comment by UrAvgDeveloper** [comment]
#2 Raised for this.
